// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function GetAllRates():Promise<Record<string, number>>;

export function GetPortRate(arg1:server.BufferKey):Promise<number>;

export function Greet(arg1:string):Promise<string>;
