// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function DUMMYGetIPConnectionDetails(arg1:server.IPConnection):Promise<string>;

export function GetAllConnectedIPs():Promise<Record<string, server.IPConnection>>;

export function GetAllRates():Promise<Record<string, number>>;

export function GetLogs(arg1:string):Promise<Array<string>>;

export function GetPortAverage(arg1:server.BufferKey):Promise<number>;

export function GetPortAverageB(arg1:server.BufferKey):Promise<number>;

export function GetPortRate(arg1:server.BufferKey):Promise<number>;

export function Greet(arg1:string):Promise<string>;
