// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DUMMYGetIPConnectionDetails(arg1) {
  return window['go']['main']['App']['DUMMYGetIPConnectionDetails'](arg1);
}

export function GetAllConnectedIPs() {
  return window['go']['main']['App']['GetAllConnectedIPs']();
}

export function GetAllRates() {
  return window['go']['main']['App']['GetAllRates']();
}

export function GetIPConnectionData(arg1) {
  return window['go']['main']['App']['GetIPConnectionData'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetPortAverage(arg1) {
  return window['go']['main']['App']['GetPortAverage'](arg1);
}

export function GetPortAverageB(arg1) {
  return window['go']['main']['App']['GetPortAverageB'](arg1);
}

export function GetPortRate(arg1) {
  return window['go']['main']['App']['GetPortRate'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
